// prettier-ignore
export const LOAD_USER_INFO = {
  _:     'LOAD_USER_INFO',
  START: 'LOAD_USER_INFO_START',
  FAIL:  'LOAD_USER_INFO_FAIL',
  OK:    'LOAD_USER_INFO_OK',
};

// prettier-ignore
export const LOGIN_FORM_SUBMIT = {
  _:     'LOGIN_FORM_SUBMIT',
  START: 'LOGIN_FORM_SUBMIT_START',
  OK:    'LOGIN_FORM_SUBMIT_OK',
  FAIL:  'LOGIN_FORM_SUBMIT_FAIL',
};

// prettier-ignore
export const REGISTER_FORM_SUBMIT = {
  _:     'REGISTER_FORM_SUBMIT',
  START: 'REGISTER_FORM_SUBMIT_START',
  OK:    'REGISTER_FORM_SUBMIT_OK',
  FAIL:  'REGISTER_FORM_SUBMIT_FAIL',
};

// prettier-ignore
export const RESET_PWD_FORM_SUBMIT = {
  _:     'RESET_PWD_FORM_SUBMIT',
  START: 'RESET_PWD_FORM_SUBMIT_START',
  OK:    'RESET_PWD_FORM_SUBMIT_OK',
  FAIL:  'RESET_PWD_FORM_SUBMIT_FAIL',
};

// prettier-ignore
export const RESET_PWD_SEND_SMS_SUBMIT = {
  _:     'RESET_PWD_SEND_SMS_SUBMIT',
  START: 'RESET_PWD_SEND_SMS_START',
  OK:    'RESET_PWD_SEND_SMS_OK',
  FAIL:  'RESET_PWD_SEND_SMS_FAIL',
};

// prettier-ignore
export const REGISITER_SEND_SMS_SUBMIT = {
  _:     'REGISITER_SEND_SMS_SUBMIT',
  START: 'REGISITER_SEND_SMS_SUBMIT_START',
  OK:    'REGISITER_SEND_SMS_SUBMIT_OK',
  FAIL:  'REGISITER_SEND_SMS_SUBMIT_FAIL',
};

// prettier-ignore
export const DETAIL_FORM_SUBMIT = {
  _:     'DETAIL_FORM_SUBMIT',
  START: 'DETAIL_FORM_SUBMIT_START',
  OK:    'DETAIL_FORM_SUBMIT_OK',
  FAIL:  'DETAIL_FORM_SUBMIT_FAIL',
};

// prettier-ignore
export const NEW_TEAM_FORM_SUBMIT = {
  _:     'NEW_TEAM_FORM_SUBMIT',
  START: 'NEW_TEAM_FORM_SUBMIT_START',
  OK:    'NEW_TEAM_FORM_SUBMIT_OK',
  FAIL:  'NEW_TEAM_FORM_SUBMIT_FAIL',
};

// prettier-ignore
export const JOIN_TEAM_FORM_SUBMIT = {
  _:     'JOIN_TEAM_FORM_SUBMIT',
  START: 'JOIN_TEAM_FORM_SUBMIT_START',
  OK:    'JOIN_TEAM_FORM_SUBMIT_OK',
  FAIL:  'JOIN_TEAM_FORM_SUBMIT_FAIL',
};

export const SHOW_APP_VIEW = 'SHOW_APP_VIEW';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_NOT_LOGGED_IN = 'SET_NOT_LOGGED_IN';
